const DOCS_URL = "https://github.com/BrunoV21/FerrisGrid-CLI/tree/main/docs/official";
const COMMAND_DOCS_URL = "https://github.com/BrunoV21/FerrisGrid-CLI/blob/main/docs/official/commands";
const AGENT_DOCS_URL = "https://github.com/BrunoV21/FerrisGrid-CLI/blob/main/docs/official/agents.md";

export type HelpTopic = "root" | "observe" | "act" | "doctor" | "recap" | "clear";

export function isHelpRequest(args: string[]): boolean {
  return args.some((arg) => arg === "-h" || arg === "--help" || arg === "help");
}

export function helpText(topic: HelpTopic): string {
  switch (topic) {
    case "observe":
      return `FerrisGrid observe\n\nCapture the current desktop state and print agent-readable Markdown with screenshot paths, screen metadata, and normalized coordinate mapping.\n\nDocs: ${COMMAND_DOCS_URL}/observe.md\n\nUsage:\n  ferrisgrid observe [options]\n\nOptions:\n  --output-dir <path>            Trace root. Default: .ferrisgrid\n  --session <name-or-path>       Create or resume a named session.\n  --screen-id <screen-id>        Capture only one screen, for example screen-1.\n  --backend <name>               native, native-linux-x11, native-macos, fake.\n  --format <jpg|png>             Screenshot format. Default: jpg.\n  --grid-overlay <true|false>    Stamp coordinate grid on screenshots. Default: true.\n  --resolution <preset|pixels>   fast, balanced, detail, native, or max edge pixels.\n  --max-image-edge <pixels|native>\n  --no-downsample                Keep native screenshot dimensions.\n  -h, --help                     Show this help.\n`;
    case "act":
      return `FerrisGrid act\n\nExecute exactly one compact Markdown action, then capture and print the updated screen state.\n\nDocs: ${COMMAND_DOCS_URL}/act.md\n\nUsage:\n  ferrisgrid act --file action.md [options]\n  ferrisgrid act [options] < action.md\n\nOptions:\n  --file <path>                  Read compact Markdown action from this file. Otherwise stdin.\n  --dry-run                      Validate and parse without emitting OS input.\n  --output-dir <path>            Trace root. Default: .ferrisgrid\n  --session <name-or-path>       Use an existing session. Default: latest session.\n  --screen-id <screen-id>        Default target for pointer actions that omit screen_id.\n  --backend <name>               native, native-linux-x11, native-macos, fake.\n  --format <jpg|png>             Post-action screenshot format. Default: jpg.\n  --grid-overlay <true|false>    Stamp coordinate grid on post-action screenshots. Default: true.\n  --resolution <preset|pixels>   fast, balanced, detail, native, or max edge pixels.\n  --max-image-edge <pixels|native>\n  --no-downsample                Keep native screenshot dimensions.\n  -h, --help                     Show this help.\n\nRequired action format:\n  Use compact Markdown key/value lines. JSON is rejected.\n  For active actions, status defaults to action when omitted.\n\nCommon fields:\n  status: action | done | fail\n  action: click | double_click | right_click | move_mouse | drag | scroll | type | press_key | hotkey | wait\n  screen_id: screen-1\n  wait_after_ms: 500\n`;
    case "doctor":
      return `FerrisGrid doctor\n\nCheck capture, input, screen discovery, output directory, and ffmpeg availability.\n\nDocs: ${COMMAND_DOCS_URL}/doctor.md\n\nUsage:\n  ferrisgrid doctor [options]\n\nOptions:\n  --output-dir <path>            Trace root to create/check. Default: .ferrisgrid\n  --backend <name>               native, native-linux-x11, native-macos, fake.\n  -h, --help                     Show this help.\n`;
    case "recap":
      return `FerrisGrid recap\n\nGenerate human-review artifacts from an existing local session directory.\n\nDocs: ${COMMAND_DOCS_URL}/recap.md\n\nUsage:\n  ferrisgrid recap <session_path> [options]\n\nOptions:\n  --video mp4                    Also export an MP4 session video.\n  --framerate <fps>              Video frames per second. Default: 2.\n  --fps <fps>                    Alias for --framerate.\n  -h, --help                     Show this help.\n`;
    case "clear":
      return `FerrisGrid clear\n\nRemove a FerrisGrid output directory.\n\nDocs: ${COMMAND_DOCS_URL}/clear.md\n\nUsage:\n  ferrisgrid clear [options]\n\nOptions:\n  --output-dir <path>            Directory to remove. Default: .ferrisgrid\n  --force                        Required for custom output directories.\n  -h, --help                     Show this help.\n\nSafety:\n  - Refuses empty paths, current directory, and filesystem root.\n  - Refuses custom output directories unless --force is present.\n`;
    case "root":
      return rootHelp();
  }
}

function rootHelp(): string {
  return `FerrisGrid\n\nSingle-step visual computer control for local agents.\n\nAgent loop:\n  1. Run \`ferrisgrid observe\`.\n  2. Inspect the screenshot path and coordinate metadata from stdout.\n  3. Write one compact Markdown action file.\n  4. Run \`ferrisgrid act --file .ferrisgrid/action.md\`.\n  5. Inspect the returned post-action screenshot path and repeat.\n\nDocs for humans:\n  ${DOCS_URL}\n  Commands: ${COMMAND_DOCS_URL}\nDocs for agents:\n  ${AGENT_DOCS_URL}\n\nUsage:\n  ferrisgrid observe [options]\n  ferrisgrid act [options] [--file action.md]\n  ferrisgrid doctor [options]\n  ferrisgrid recap <session_path> [options]\n  ferrisgrid clear [options]\n  ferrisgrid help [observe|act|doctor|recap|clear]\n\nCommand help:\n  ferrisgrid observe --help\n  ferrisgrid act --help\n  ferrisgrid doctor --help\n  ferrisgrid recap --help\n  ferrisgrid clear --help\n\nCommon output/capture options:\n  --output-dir <path>            Trace root. Default: .ferrisgrid\n  --backend <name>               native, native-linux-x11, native-macos, fake.\n  --format <jpg|png>             Screenshot format. Default: jpg.\n  --grid-overlay <true|false>    Stamp coordinate grid on screenshots. Default: true.\n  --resolution <preset|pixels>   fast, balanced, detail, native, or max edge pixels.\n  --max-image-edge <pixels|native>\n  --no-downsample                Keep native screenshot dimensions.\n\nEnvironment defaults:\n  FERRISGRID_OUTPUT_DIR          Default trace root.\n  FERRISGRID_DEFAULT_SCREEN_ID   Default observe screen and act pointer-action target.\n  FERRISGRID_MAX_IMAGE_EDGE      Default max edge or native.\n  FERRISGRID_BACKEND             Default backend name.\n\nCoordinate protocol:\n  - stdout declares coordinate_mode, range, screen IDs, screenshot paths, and metadata paths.\n  - Use normalized-1000 coordinates: x=0 y=0 is top-left, x=1000 y=1000 is bottom-right.\n\nAction Markdown summary:\n  status: action\n  action: click | double_click | right_click | move_mouse | drag | scroll | type | press_key | hotkey | wait\n  screen_id: screen-1\n  wait_after_ms: 500\n`;
}
